apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-use-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-use-cpu
  template:
    metadata:
      labels:
        app: deployment-use-cpu
    spec:
      # Don't wait (SIGTERM) just kill (SIGKILL)
      terminationGracePeriodSeconds: 0
      containers:
        - name: use-cpu
          image: alpine:latest
          command: ["/bin/sh", "-c", "--"]
          args:
            - >
              echo "I am using CPU...";
              while true; do true; done
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 50m
              memory: 128Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-use-cpu
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
